# Generated by Django 3.2.6 on 2021-08-16 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='InstitutionSupervisor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.institutionsupervisor'),
        ),
        migrations.AlterField(
            model_name='students',
            name='universityInspec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.universitysupervisor'),
        ),
    ]
