# Generated by Django 3.2.6 on 2021-08-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
